insert into Preference (id, category, name)
values(uuid(), 1, "Accidental Expressionism"),
	(uuid(), 1, "ADR"),
	(uuid(), 1, "Another Fine Asylum Production"),
	(uuid(), 1, "Another Fine Cannon Production"),
	(uuid(), 1, "Another Fine Corman Production"),
	(uuid(), 1, "Another Fine Full Moon Production"),
	(uuid(), 1, "Big Budget Slop"),
	(uuid(), 1, "Costumes by Mom"),
	(uuid(), 1, "Dead Inside Line Readings"),
	(uuid(), 1, "Gratuitous Slo-Mo"),
	(uuid(), 1, "Intrusive Camera"),
	(uuid(), 1, "Intrusive Editing"),
	(uuid(), 1, "Intrusive Foley"),
	(uuid(), 1, "Intrusive Score"),
	(uuid(), 1, "Low Budget"),
	(uuid(), 1, "No Actors Here"),
	(uuid(), 1, "No Second Takes"),
	(uuid(), 1, "No Sets Here"),
	(uuid(), 1, "Obvious Compositing"),
	(uuid(), 1, "Obvious Dummy"),
	(uuid(), 1, "Oops All Stock Footage"),
	(uuid(), 1, "Oops Good Costumes"),
	(uuid(), 1, "Oops Good Lighting"),
	(uuid(), 1, "Oops Good Makeup"),
	(uuid(), 1, "Pan Pipes"),
	(uuid(), 1, "Practical Effects"),
	(uuid(), 1, "Visible Production Gear"),
	(uuid(), 2, "Aliens"),
	(uuid(), 2, "Bees"),
	(uuid(), 2, "Cowboys"),
	(uuid(), 2, "Dinosaurs"),
	(uuid(), 2, "Furries"),
	(uuid(), 2, "Godzilla"),
	(uuid(), 2, "Jar Jar Binks"),
	(uuid(), 2, "Ninjas"),
	(uuid(), 2, "Old Child"),
	(uuid(), 2, "Robot Spiders"),
	(uuid(), 2, "Robots"),
	(uuid(), 2, "Sharks"),
	(uuid(), 2, "Shitty Puppet"),
	(uuid(), 2, "Snakes"),
	(uuid(), 2, "Supersoldiers"),
	(uuid(), 2, "Talking Things That Shouldn't Talk"),
	(uuid(), 2, "Vampires"),
	(uuid(), 2, "Werewolves"),
	(uuid(), 2, "Zombies"), 
	(uuid(), 3, "Barely a Movie"),
	(uuid(), 3, "Beating a Dead Backstory"),
	(uuid(), 3, "Beating a Dead Exposition"),
	(uuid(), 3, "Chasing Stupid Clues"),
	(uuid(), 3, "Classics Flex"),
	(uuid(), 3, "Cop Slop"),
	(uuid(), 3, "Dad-Approved"),
	(uuid(), 3, "Did You Know That Humans"),
	(uuid(), 3, "Die Hard on a"),
	(uuid(), 3, "Get the Bastards"),
	(uuid(), 3, "Gratuitous The Jump"),
	(uuid(), 3, "Hello Mr. Police"),
	(uuid(), 3, "Indiana Jones"),
	(uuid(), 3, "Is This a Robocop?"),
	(uuid(), 3, "Is This a Star War?"),
	(uuid(), 3, "Is This a Matrix?"),
	(uuid(), 3, "Is This a The Terminator?"),
	(uuid(), 3, "It Was All Dream"),
	(uuid(), 3, "Max Max"),
	(uuid(), 3, "Never Stopped to Ask If We Should"),
	(uuid(), 3, "Oops All Bits"),
	(uuid(), 3, "Oops All Peril"),
	(uuid(), 3, "Oops All Twists"),
	(uuid(), 3, "Oops All Vignettes"),
	(uuid(), 3, "Oops Fourth Act"),
	(uuid(), 3, "Plane Problems"),
	(uuid(), 3, "Quips"),
	(uuid(), 3, "Rickety Bridge"),
	(uuid(), 3, "Save the Rec Center"),
	(uuid(), 3, "Scorn Porn"),
	(uuid(), 3, "Sex Movie for Sex Perverts"),
	(uuid(), 3, "She Died for the Plot"),
	(uuid(), 3, "So That's What Killed Dinosaurs"),
	(uuid(), 3, "Somehow This Passes the Bechdel Test"),
	(uuid(), 3, "Spoiler the Black Guy Dies First"),
	(uuid(), 3, "Stupid Tarantino"),
	(uuid(), 3, "Technology Hates Us"),
	(uuid(), 3, "That's the Name of the Movie"),
	(uuid(), 3, "The Friends We Made Along the Way"),
	(uuid(), 3, "The Real Power Was Love"),
	(uuid(), 3, "The Real Power Was Testosterone"),
	(uuid(), 3, "The Really Killed That Kid"),
	(uuid(), 3, "Unnecessary Narration"),
	(uuid(), 3, "Wake Up Sheeple"),
	(uuid(), 4, "Al Pacino"),
	(uuid(), 4, "Brendan Fraser"),
	(uuid(), 4, "Chuck Norris"),
	(uuid(), 4, "Gary Busey"),
	(uuid(), 4, "Gene Simmons"),
	(uuid(), 4, "Hulk Hogan"),
	(uuid(), 4, "Ice-T"),
	(uuid(), 4, "Jackie Chan"),
	(uuid(), 4, "Jason Statham"),
	(uuid(), 4, "John Cusack"),
	(uuid(), 4, "Keanu"),
	(uuid(), 4, "Kelsey Grammer"),
	(uuid(), 4, "Luc Besson"),
	(uuid(), 4, "M. Night Shyamalan"),
	(uuid(), 4, "Michael Crichton"),
	(uuid(), 4, "Milla Jovovich"),
	(uuid(), 4, "Nic Cage"),
	(uuid(), 4, "Oscar Isaac"),
	(uuid(), 4, "Schwarzenegger"),
	(uuid(), 4, "Seagal"),
	(uuid(), 4, "Stephen King"),
	(uuid(), 4, "The Rock"),
	(uuid(), 4, "Travolta"),
	(uuid(), 4, "Van Damme"),
	(uuid(), 4, "Wachowskis"),
	(uuid(), 5, "Frosted Tips"),
	(uuid(), 5, "Mullets"),
	(uuid(), 5, "White People with Dreads"),
	(uuid(), 5, "Wow What a Wig"),
	(uuid(), 6, "Butts"),
	(uuid(), 6, "Can't Unsee"),
	(uuid(), 6, "CG"),
	(uuid(), 6, "Christmas"),
	(uuid(), 6, "Direct to Home Video"),
	(uuid(), 6, "Feet"),
	(uuid(), 6, "Halloween"),
	(uuid(), 6, "Holiday"),
	(uuid(), 6, "I Should Fire My Agent"),
	(uuid(), 6, "I Wonder If That's the Bad Guy"),
	(uuid(), 6, "Made for TV"),
	(uuid(), 6, "Mouthbreather Theater"),
	(uuid(), 6, "No Actors Really Trying"),
	(uuid(), 6, "Romance Through Space and Time"),
	(uuid(), 6, "Smooth Furry Hell"),
	(uuid(), 6, "Unexpected Incestuous Undertones"),
	(uuid(), 6, "You Have to See It But You Won't Like It"),
	(uuid(), 7, "Animal Cruelty"),
	(uuid(), 7, "Bad Lighting"),
	(uuid(), 7, "Bad Sound Mix"),
	(uuid(), 7, "Beef Protein"),
	(uuid(), 7, "Casual Ableism"),
	(uuid(), 7, "Casual Fatphobia"),
	(uuid(), 7, "Casual Racism"),
	(uuid(), 7, "Cool World"),
	(uuid(), 7, "Crusty"),
	(uuid(), 7, "Everyone's on Board"),
	(uuid(), 7, "Goes Down Smooth"),
	(uuid(), 7, "Groaner"),
	(uuid(), 7, "Hateful"),
	(uuid(), 7, "Inscrutable Accent"),
	(uuid(), 7, "Intentional Slop"),
	(uuid(), 7, "It's a Musical"),
	(uuid(), 7, "Kicks and Punches"),
	(uuid(), 7, "Not Slop"),
	(uuid(), 7, "Oops Good Film"),
	(uuid(), 7, "Oops Good First Act"),
	(uuid(), 7, "Oops Good Score"),
	(uuid(), 7, "Oops Good Third Act"),
	(uuid(), 7, "Overt Sponsorship"),
	(uuid(), 7, "Quotable Quotes"),
	(uuid(), 7, "Ride the Fast Forward"),
	(uuid(), 7, "Shameless Display of Movie"),
	(uuid(), 7, "Sloppy Premise Good Execution"),
	(uuid(), 7, "Splosions!"),
	(uuid(), 7, "Stylish"),
	(uuid(), 7, "That One Actor is Really Trying"),
	(uuid(), 7, "That's Not a Name"),
	(uuid(), 7, "That's Not Slang"),
	(uuid(), 7, "This Movie Has Everything"),
	(uuid(), 7, "This Movie Love Women"),
	(uuid(), 7, "Unexpectedly Grim"),
	(uuid(), 7, "Unlikeable Protagonist"),
	(uuid(), 7, "Wow So Sexy"),
	(uuid(), 7, "Wow What a Twist"),
	(uuid(), 8, "A Little Too Cronenberg"),
	(uuid(), 8, "Animated"),
	(uuid(), 8, "Auteur"),
	(uuid(), 8, "Baffling"),
	(uuid(), 8, "Bromance"),
	(uuid(), 8, "Campy"),
	(uuid(), 8, "Ew Don't Kiss Him"),
	(uuid(), 8, "Extreme Sports"),
	(uuid(), 8, "Faaaaabulous"),
	(uuid(), 8, "Figurative Hell"),
	(uuid(), 8, "Gore"),
	(uuid(), 8, "Great Stunts"),
	(uuid(), 8, "Homoerotic Undertones"),
	(uuid(), 8, "Hot for Guns"),
	(uuid(), 8, "Just Yelling"),
	(uuid(), 8, "Literal Hell"),
	(uuid(), 8, "No Homo"),
	(uuid(), 8, "Ooh an Original Song"),
	(uuid(), 8, "Oops Music Video"),
	(uuid(), 8, "Queer Icon"),
	(uuid(), 8, "Sincere"),
	(uuid(), 8, "Slop from Abroad"),
	(uuid(), 8, "Stupid Premise Stupid Execution"),
	(uuid(), 8, "Unexpectedly Garbage Cameo"),
	(uuid(), 8, "Unnecessary Nudity");
	
	
	
	
	